version: '3.7'

services:
  postgres:
    image: postgres:16.3
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: flutter
      POSTGRES_PASSWORD: "2aaG6y0dQGlkUZdxHzhEjz41bofidPJ7"
    volumes:
      - flutter_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "S00Cbyz5xNS0RouGFDO6lPYoOOTPFc39"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  flutter_data:
