name: Serverpod Backend

on:
  workflow_dispatch:

jobs:
  start-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: sudo apt-get install -y docker-compose

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install Serverpod Dependencies
        working-directory: flutter_server
        run: |
          dart pub get

      - name: Start Serverpod Backend with Docker
        working-directory: flutter_server
        run: |
          docker compose up --build --detach

      - name: Create passwords file
        working-directory: flutter_server
        run: echo "${{ secrets.SERVERPOD_PASSWORDS }}" > config/passwords.yaml

      - name: Apply Migrations
        working-directory: flutter_server
        run: |
          dart bin/main.dart --apply-migrations

      - name: Verify Serverpod is Running
        working-directory: flutter_server
        run: curl -f http://localhost:8080/health || exit 1
